"grpc":
  "network": "tcp"
  "port": 50054

"http":
  "port": 8080

"adrepo":
  "username": "postgres"
  "password": "postgres"
  "host": "adrepo"
  "port": "5432"
  "dbname": "postgres"
  "sslmode": "disable"
