"grpc":
  "network": "tcp"
  "port": 50054

"http":
  "host": "app"
  "port": 8080

"adrepo":
  "username": "postgres"
  "password": "postgres"
  "host": "adrepo"
  "port": "5432"
  "dbname": "postgres"
  "sslmode": "disable"

"user_repo":
  "host": "user_repo"
  "port": "27017"
  "dbname": "user_repo"
  "collection": "users"
