version: '3'

services:
  app:
    build: ./
    command: ./app
    ports:
      - "8080:8080"
      - "50054:50054"
    depends_on:
      - adrepo
      - user_repo

  adrepo:
    restart: always
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  user_repo:
    restart: always
    image: mongo:6.0
    ports:
      - "27017:27017"

volumes:
  db-data:
